//
//  defines.h
//  DnDrD
//
//  Created by Nelson Frank on 2016-11-11.
//  Copyright © 2016 COMP 345. All rights reserved.
//

#ifndef defines_h
#define defines_h

#define WINDOW_HEIGHT NUMBER_BLOCKS_DISPLAYED_Y * BLOCK_SIZE + TOOLBAR_PANE_HEIGHT
#define WINDOW_WIDTH NUMBER_BLOCKS_DISPLAYED_X * BLOCK_SIZE
#define WINDOW_NAME "DnDrD"

#define NUMBER_BLOCKS_DISPLAYED_Y 15
#define NUMBER_BLOCKS_DISPLAYED_X 25

#define TOOLBAR_PANE_HEIGHT 2 * BLOCK_SIZE

#define FRAMES_PER_SECOND 10
#define FRAME_RATE 1000/FRAMES_PER_SECOND

#define MENU_BUTTON_SCALE 3/4
#define MENU_BUTTON_WIDTH 382 * MENU_BUTTON_SCALE
#define MENU_BUTTON_HEIGHT 157  * MENU_BUTTON_SCALE
#define MENU_BUTTON_Y_OFFSET 50
#define MENU_BUTTON_SPACING 30

#define BLOCK_SIZE 50

#define STONE_GROUND_X_SELECTION 0
#define STONE_GROUND_Y_SELECTION 0
#define STONE_GROUND_SIZE 128

#define HERO_IMAGE_SPRITE_SIZE 128


#endif /* defines_h */
